# Generated by Django 5.2.5 on 2025-08-25 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders_app', '0002_order_delivery_time_in_days_order_features_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='offer_type',
        ),
    ]
