# Generated by Django 5.2.5 on 2025-09-02 10:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers_app', '0004_alter_offer_user'),
        ('orders_app', '0003_remove_order_offer_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivery_time_in_days',
        ),
        migrations.RemoveField(
            model_name='order',
            name='features',
        ),
        migrations.RemoveField(
            model_name='order',
            name='revisions',
        ),
        migrations.RemoveField(
            model_name='order',
            name='title',
        ),
        migrations.AddField(
            model_name='order',
            name='offer_detail',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='offers_app.offerdetail'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_orders', to=settings.AUTH_USER_MODEL),
        ),
    ]
