# Generated by Django 5.2.5 on 2025-08-12 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_rename_fullname_userprofile_username_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='username',
        ),
    ]
