# Generated by Django 5.2.5 on 2025-08-12 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0004_userprofile_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='email',
        ),
    ]
