# Generated by Django 5.2.5 on 2025-09-02 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0008_userprofile_created_at_userprofile_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='uploaded_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
