# Generated by Django 5.2.5 on 2025-08-25 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerdetail',
            name='delivery_time_in_days',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='offerdetail',
            name='features',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='offerdetail',
            name='offer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='details', to='offers_app.offer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='offerdetail',
            name='offer_type',
            field=models.CharField(choices=[('basic', 'Basic'), ('standard', 'Standard'), ('premium', 'Premium')], default=1, max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='offerdetail',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='offerdetail',
            name='revisions',
            field=models.PositiveIntegerField(),
        ),
    ]
